version: "3.44"

tasks:
  premake:
    desc: Generate project build files
    sources:
      - src/**/*.hpp
      - src/**/*.cpp
      - src/**/*.h
      - src/**/*.c
      - premake5.lua
    generates:
      - build/Makefile
      - build/*.make
    cmd: premake gmake2

  build-debug:
    desc: Build project (Debug)
    sources:
      - build/Makefile
      - build/*.make
    generates:
      - build/obj/*.o
    deps:
      - premake
    cmd: make -C build config=debug -j4 particles

  build-release:
    desc: Build project (Release)
    sources:
      - build/Makefile
      - build/*.make
    generates:
      - build/obj/*.o
    aliases:
      - build
    deps:
      - premake
    cmd: make -C build config=release -j4 particles

  run-debug:
    desc: Run project
    deps:
      - build-debug
    cmd: build/bin/Debug/particles

  run-release:
    desc: Run project
    deps:
      - build-release
    aliases:
      - run
    cmd: build/bin/Release/particles

  clean:
    desc: Clean builds
    cmd: make -C build clean; rm -fr build
