version: "3.44"

vars:
  TESTS:
    - test_uniformgrid
    - test_world
    - test_multicore
    - test_mailboxes
    - test_save_manager
    - test_simulation

tasks:
  premake:
    desc: Generate project build files
    sources:
      - src/**/*.hpp
      - src/**/*.cpp
      - tests/**/.cpp
      - tests/**/.hpp
      - premake5.lua
    generates:
      - build/Makefile
      - build/*.make
    cmd: premake gmake2

  build-binary:
    internal: true
    requires:
      vars: [CONFIG, PROJECT]
    sources:
      - src/**/*.hpp
      - src/**/*.cpp
      - tests/**/.cpp
      - tests/**/.hpp
      - premake5.lua
      - build/Makefile
      - build/{{.PROJECT}}.make
    generates:
      - build/bin/{{.CONFIG}}/{{.PROJECT}}
    deps:
      - premake
    cmd: make -C build config={{.CONFIG}} -j4 {{.PROJECT}}

  run-binary:
    internal: true
    requires:
      vars: [CONFIG, PROJECT]
    deps:
      - task: build-binary
        vars:
          CONFIG: "{{.CONFIG}}"
          PROJECT: "{{.PROJECT}}"
    cmd: build/bin/{{.CONFIG}}/{{.PROJECT}}

  build:debug:
    desc: Build project (Debug)
    cmds:
      - task: build-binary
        vars:
          CONFIG: debug
          PROJECT: particles

  build:release:
    desc: Build project (Release)
    aliases:
      - build
    cmds:
      - task: build-binary
        vars:
          CONFIG: release
          PROJECT: particles

  run:debug:
    desc: Run project
    cmds:
      - task: run-binary
        vars:
          CONFIG: debug
          PROJECT: particles

  run:release:
    desc: Run project
    aliases:
      - run
    cmds:
      - task: run-binary
        vars:
          CONFIG: release
          PROJECT: particles

  build:test:
    desc: Build a unit test
    requires:
      vars: [PROJECT]
    cmds:
      - task: build-binary
        vars:
          CONFIG: debug
          PROJECT: "{{.PROJECT}}"

  build:test:all:
    desc: Build all unit tests
    cmds:
      - for:
          var: TESTS
        task: build-binary
        vars:
          CONFIG: debug
          PROJECT: "{{.ITEM}}"

  test:all:
    desc: Build and run all unit tests
    deps:
      - build:test:all
    cmds:
      - for:
          var: TESTS
        task: run-binary
        vars:
          CONFIG: debug
          PROJECT: "{{.ITEM}}"

  test:
    desc: Build and run a unit test. Use `task test -- test_uniformgrid`
    cmds:
      - task: run-binary
        vars:
          CONFIG: debug
          PROJECT: "{{index .CLI_ARGS_LIST 0}}"

  clean:
    desc: Clean builds
    cmd: rm -fr build
