version: "3.44"

tasks:
  premake:
    desc: Generate project build files
    sources:
      - src/**/*.hpp
      - src/**/*.cpp
      - src/**/*.h
      - src/**/*.c
      - tests/**/.cpp
      - tests/**/.hpp
      - premake5.lua
    generates:
      - build/Makefile
      - build/*.make
    cmd: premake gmake2

  build-debug:
    desc: Build project (Debug)
    sources:
      - build/Makefile
      - build/*.make
    generates:
      - build/obj/*.o
    deps:
      - premake
    cmd: make -C build config=debug -j4 particles

  build-release:
    desc: Build project (Release)
    sources:
      - build/Makefile
      - build/*.make
    generates:
      - build/obj/*.o
    aliases:
      - build
    deps:
      - premake
    cmd: make -C build config=release -j4 particles

  run-debug:
    desc: Run project
    deps:
      - build-debug
    cmd: build/bin/Debug/particles

  run-release:
    desc: Run project
    deps:
      - build-release
    aliases:
      - run
    cmd: build/bin/Release/particles

  clean:
    desc: Clean builds
    cmd: make -C build clean; rm -fr build

  test:build:test_uniformgrid:
    desc: Build unit test test_uniformgrid
    deps:
      - premake
    cmd: make -C build config=debug -j4 test_uniformgrid

  test:run:test_uniformgrid:
    desc: Run unit test test_uniformgrid
    deps:
      - test:build:test_uniformgrid
    cmd: build/bin/Debug/test_uniformgrid

  test:build:test_world:
    desc: Build unit test test_world
    deps:
      - premake
    cmd: make -C build config=debug -j4 test_world

  test:run:test_world:
    desc: Run unit test test_world
    deps:
      - test:build:test_world
    cmd: build/bin/Debug/test_world

  test:build:test_multicore:
    desc: Build unit test test_multicore
    deps:
      - premake
    cmd: make -C build config=debug -j4 test_multicore

  test:run:test_multicore:
    desc: Run unit test test_multicore
    deps:
      - test:build:test_multicore
    cmd: build/bin/Debug/test_multicore

  test:build:test_mailboxes:
    desc: Build unit test test_mailboxes
    deps:
      - premake
    cmd: make -C build config=debug -j4 test_mailboxes

  test:run:test_mailboxes:
    desc: Run unit test test_mailboxes
    deps:
      - test:build:test_mailboxes
    cmd: build/bin/Debug/test_mailboxes

  test:build:test_save_manager:
    desc: Build unit test test_save_manager
    deps:
      - premake
    cmd: make -C build config=debug -j4 test_save_manager

  test:run:test_save_manager:
    desc: Run unit test test_save_manager
    deps:
      - test:build:test_save_manager
    cmd: build/bin/Debug/test_save_manager

  test:build:test_simulation:
    desc: Build unit test test_simulation
    deps:
      - premake
    cmd: make -C build config=debug -j4 test_simulation

  test:run:test_simulation:
    desc: Run unit test test_simulation
    deps:
      - test:build:test_simulation
    cmd: build/bin/Debug/test_simulation

  test:all:
    desc: Build and run all unit tests
    aliases:
      - test
    cmds:
      - task: test:run:test_uniformgrid
      - task: test:run:test_world
      - task: test:run:test_multicore
      - task: test:run:test_mailboxes
      - task: test:run:test_save_manager
      - task: test:run:test_simulation
