// ImGui Style
// Generated by Style Editor
#include <imgui.h>

void setup_style() {
    ImGuiStyle &style = ImGui::GetStyle();

    // Font scaling
    style.FontSizeBase = 13.0f;
    style.FontScaleMain = 1.2000000477f;
    style.FontScaleDpi = 1.0f;

    // Alpha
    style.Alpha = 1.0f;
    style.DisabledAlpha = 0.6000000238f;

    // Window
    style.WindowPadding = ImVec2(8.0f, 8.0f);
    style.WindowRounding = 0.0f;
    style.WindowBorderSize = 1.0f;
    style.WindowBorderHoverPadding = 4.0f;
    style.WindowMinSize = ImVec2(32.0f, 32.0f);
    style.WindowTitleAlign = ImVec2(0.0f, 0.5f);
    style.WindowMenuButtonPosition = ImGuiDir_Left;

    // Child
    style.ChildRounding = 0.0f;
    style.ChildBorderSize = 1.0f;

    // Popup
    style.PopupRounding = 0.0f;
    style.PopupBorderSize = 1.0f;

    // Frame
    style.FramePadding = ImVec2(4.0f, 3.0f);
    style.FrameRounding = 0.0f;
    style.FrameBorderSize = 0.0f;

    // Item spacing
    style.ItemSpacing = ImVec2(8.0f, 4.0f);
    style.ItemInnerSpacing = ImVec2(4.0f, 4.0f);
    style.CellPadding = ImVec2(4.0f, 2.0f);
    style.TouchExtraPadding = ImVec2(0.0f, 0.0f);

    // Indentation
    style.IndentSpacing = 21.0f;
    style.ColumnsMinSpacing = 6.0f;

    // Scrollbar
    style.ScrollbarSize = 14.0f;
    style.ScrollbarRounding = 1.0f;
    style.ScrollbarPadding = 4.0f;

    // Grab
    style.GrabMinSize = 12.0f;
    style.GrabRounding = 0.0f;
    style.LogSliderDeadzone = 4.0f;

    // Image
    style.ImageBorderSize = 0.0f;

    // Tab
    style.TabRounding = 0.0f;
    style.TabBorderSize = 0.0f;
    style.TabMinWidthBase = 1.0f;
    style.TabMinWidthShrink = 80.0f;
    style.TabCloseButtonMinWidthSelected = -1.0f;
    style.TabCloseButtonMinWidthUnselected = 0.0f;
    style.TabBarBorderSize = 1.0f;
    style.TabBarOverlineSize = 1.0f;

    // Table
    style.TableAngledHeadersAngle = 0.6108652353f;
    style.TableAngledHeadersTextAlign = ImVec2(0.5f, 0.0f);

    // Tree lines
    style.TreeLinesFlags = ImGuiTreeNodeFlags_DrawLinesNone;
    style.TreeLinesSize = 1.0f;
    style.TreeLinesRounding = 0.0f;

    // Color button
    style.ColorButtonPosition = ImGuiDir_Right;

    // Text alignment
    style.ButtonTextAlign = ImVec2(0.5f, 0.5f);
    style.SelectableTextAlign = ImVec2(0.0f, 0.0f);

    // Separator text
    style.SeparatorTextBorderSize = 3.0f;
    style.SeparatorTextAlign = ImVec2(0.0f, 0.5f);
    style.SeparatorTextPadding = ImVec2(20.0f, 3.0f);

    // Display
    style.DisplayWindowPadding = ImVec2(19.0f, 19.0f);
    style.DisplaySafeAreaPadding = ImVec2(3.0f, 3.0f);
    style.MouseCursorScale = 1.0f;

    // Anti-aliasing
    style.AntiAliasedLines = true;
    style.AntiAliasedLinesUseTex = true;
    style.AntiAliasedFill = true;

    // Tessellation
    style.CurveTessellationTol = 1.25f;
    style.CircleTessellationMaxError = 0.3000000119f;

    // Hover behaviors
    style.HoverStationaryDelay = 0.150000006f;
    style.HoverDelayShort = 0.150000006f;
    style.HoverDelayNormal = 0.400000006f;

    // Colors - Dark Brutalist Theme
    // Base: Near-black backgrounds, soft off-white text, bright clickable
    // elements with bold cyan accent
    style.Colors[ImGuiCol_Text] = ImVec4(0.9f, 0.9f, 0.9f, 1.0f);
    style.Colors[ImGuiCol_TextDisabled] = ImVec4(0.5f, 0.5f, 0.5f, 1.0f);
    style.Colors[ImGuiCol_WindowBg] = ImVec4(0.05f, 0.05f, 0.05f, 1.0f);
    style.Colors[ImGuiCol_ChildBg] = ImVec4(0.0f, 0.0f, 0.0f, 0.0f);
    style.Colors[ImGuiCol_PopupBg] = ImVec4(0.08f, 0.08f, 0.08f, 1.0f);
    style.Colors[ImGuiCol_Border] = ImVec4(0.25f, 0.25f, 0.25f, 1.0f);
    style.Colors[ImGuiCol_BorderShadow] = ImVec4(0.0f, 0.0f, 0.0f, 0.0f);
    style.Colors[ImGuiCol_FrameBg] = ImVec4(0.22f, 0.22f, 0.22f, 1.0f);
    style.Colors[ImGuiCol_FrameBgHovered] = ImVec4(0.28f, 0.28f, 0.28f, 1.0f);
    style.Colors[ImGuiCol_FrameBgActive] = ImVec4(0.2f, 0.5f, 0.5f, 0.4f);
    style.Colors[ImGuiCol_TitleBg] = ImVec4(0.0f, 0.0f, 0.0f, 1.0f);
    style.Colors[ImGuiCol_TitleBgActive] = ImVec4(0.0f, 0.0f, 0.0f, 1.0f);
    style.Colors[ImGuiCol_TitleBgCollapsed] = ImVec4(0.0f, 0.0f, 0.0f, 0.6f);
    style.Colors[ImGuiCol_MenuBarBg] = ImVec4(0.08f, 0.08f, 0.08f, 1.0f);
    style.Colors[ImGuiCol_ScrollbarBg] = ImVec4(0.02f, 0.02f, 0.02f, 1.0f);
    style.Colors[ImGuiCol_ScrollbarGrab] = ImVec4(0.4f, 0.4f, 0.4f, 1.0f);
    style.Colors[ImGuiCol_ScrollbarGrabHovered] =
        ImVec4(0.5f, 0.5f, 0.5f, 1.0f);
    style.Colors[ImGuiCol_ScrollbarGrabActive] = ImVec4(0.6f, 0.6f, 0.6f, 1.0f);
    style.Colors[ImGuiCol_CheckMark] = ImVec4(0.3f, 0.65f, 0.65f, 1.0f);
    style.Colors[ImGuiCol_SliderGrab] = ImVec4(0.25f, 0.6f, 0.6f, 1.0f);
    style.Colors[ImGuiCol_SliderGrabActive] = ImVec4(0.3f, 0.65f, 0.65f, 1.0f);
    style.Colors[ImGuiCol_Button] = ImVec4(0.3f, 0.3f, 0.3f, 1.0f);
    style.Colors[ImGuiCol_ButtonHovered] = ImVec4(0.2f, 0.55f, 0.55f, 1.0f);
    style.Colors[ImGuiCol_ButtonActive] = ImVec4(0.25f, 0.6f, 0.6f, 1.0f);
    style.Colors[ImGuiCol_Header] = ImVec4(0.25f, 0.25f, 0.25f, 1.0f);
    style.Colors[ImGuiCol_HeaderHovered] = ImVec4(0.2f, 0.5f, 0.5f, 1.0f);
    style.Colors[ImGuiCol_HeaderActive] = ImVec4(0.25f, 0.6f, 0.6f, 1.0f);
    style.Colors[ImGuiCol_Separator] = ImVec4(0.35f, 0.35f, 0.35f, 1.0f);
    style.Colors[ImGuiCol_SeparatorHovered] = ImVec4(0.2f, 0.55f, 0.55f, 1.0f);
    style.Colors[ImGuiCol_SeparatorActive] = ImVec4(0.25f, 0.6f, 0.6f, 1.0f);
    style.Colors[ImGuiCol_ResizeGrip] = ImVec4(0.3f, 0.3f, 0.3f, 1.0f);
    style.Colors[ImGuiCol_ResizeGripHovered] = ImVec4(0.2f, 0.55f, 0.55f, 1.0f);
    style.Colors[ImGuiCol_ResizeGripActive] = ImVec4(0.25f, 0.6f, 0.6f, 1.0f);
    style.Colors[ImGuiCol_InputTextCursor] = ImVec4(0.3f, 0.65f, 0.65f, 1.0f);
    style.Colors[ImGuiCol_TabHovered] = ImVec4(0.2f, 0.5f, 0.5f, 1.0f);
    style.Colors[ImGuiCol_Tab] = ImVec4(0.25f, 0.25f, 0.25f, 1.0f);
    style.Colors[ImGuiCol_TabSelected] = ImVec4(0.25f, 0.6f, 0.6f, 1.0f);
    style.Colors[ImGuiCol_TabSelectedOverline] =
        ImVec4(0.3f, 0.65f, 0.65f, 1.0f);
    style.Colors[ImGuiCol_TabDimmed] = ImVec4(0.15f, 0.15f, 0.15f, 1.0f);
    style.Colors[ImGuiCol_TabDimmedSelected] =
        ImVec4(0.15f, 0.45f, 0.45f, 1.0f);
    style.Colors[ImGuiCol_TabDimmedSelectedOverline] =
        ImVec4(0.25f, 0.6f, 0.6f, 1.0f);
    style.Colors[ImGuiCol_PlotLines] = ImVec4(0.7f, 0.7f, 0.7f, 1.0f);
    style.Colors[ImGuiCol_PlotLinesHovered] = ImVec4(0.25f, 0.6f, 0.6f, 1.0f);
    style.Colors[ImGuiCol_PlotHistogram] = ImVec4(0.3f, 0.65f, 0.65f, 1.0f);
    style.Colors[ImGuiCol_PlotHistogramHovered] =
        ImVec4(0.25f, 0.6f, 0.6f, 1.0f);
    style.Colors[ImGuiCol_TableHeaderBg] = ImVec4(0.1f, 0.1f, 0.1f, 1.0f);
    style.Colors[ImGuiCol_TableBorderStrong] = ImVec4(0.3f, 0.3f, 0.3f, 1.0f);
    style.Colors[ImGuiCol_TableBorderLight] = ImVec4(0.2f, 0.2f, 0.2f, 1.0f);
    style.Colors[ImGuiCol_TableRowBg] = ImVec4(0.0f, 0.0f, 0.0f, 0.0f);
    style.Colors[ImGuiCol_TableRowBgAlt] = ImVec4(1.0f, 1.0f, 1.0f, 0.03f);
    style.Colors[ImGuiCol_TextLink] = ImVec4(0.25f, 0.6f, 0.6f, 1.0f);
    style.Colors[ImGuiCol_TextSelectedBg] = ImVec4(0.2f, 0.55f, 0.55f, 0.4f);
    style.Colors[ImGuiCol_TreeLines] = ImVec4(0.3f, 0.3f, 0.3f, 1.0f);
    style.Colors[ImGuiCol_DragDropTarget] = ImVec4(0.3f, 0.65f, 0.65f, 0.9f);
    style.Colors[ImGuiCol_NavCursor] = ImVec4(0.3f, 0.65f, 0.65f, 1.0f);
    style.Colors[ImGuiCol_NavWindowingHighlight] =
        ImVec4(0.25f, 0.6f, 0.6f, 0.7f);
    style.Colors[ImGuiCol_NavWindowingDimBg] = ImVec4(0.0f, 0.0f, 0.0f, 0.8f);
    style.Colors[ImGuiCol_ModalWindowDimBg] = ImVec4(0.0f, 0.0f, 0.0f, 0.85f);
}
